<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="EF-BS-00533" name="org.example.testRunner.Runners" tests="19" failures="3" timestamp="2022-08-09T17:42:50 EET" time="380.267" errors="0">
  <testcase name="runScenario" time="14.113" classname="org.example.testRunner.Runners"/>
  <system-out/>
  <testcase name="runScenario" time="19.116" classname="org.example.testRunner.Runners"/>
  <system-out/>
  <testcase name="runScenario" time="32.656" classname="org.example.testRunner.Runners"/>
  <system-out/>
  <testcase name="runScenario" time="34.416" classname="org.example.testRunner.Runners"/>
  <system-out/>
  <testcase name="runScenario" time="13.530" classname="org.example.testRunner.Runners"/>
  <system-out/>
  <testcase name="runScenario" time="27.143" classname="org.example.testRunner.Runners"/>
  <system-out/>
  <testcase name="runScenario" time="18.269" classname="org.example.testRunner.Runners"/>
  <system-out/>
  <testcase name="runScenario" time="12.962" classname="org.example.testRunner.Runners"/>
  <system-out/>
  <testcase name="runScenario" time="21.183" classname="org.example.testRunner.Runners"/>
  <system-out/>
  <testcase name="runScenario" time="16.977" classname="org.example.testRunner.Runners">
    <failure type="java.lang.AssertionError" message="expected [https://demo.nopcommerce.com/new-online-store-is-open] but found [https://demo.nopcommerce.com/news/rss/1]">
      <![CDATA[java.lang.AssertionError: expected [https://demo.nopcommerce.com/new-online-store-is-open] but found [https://demo.nopcommerce.com/news/rss/1]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at org.example.stepDefs.D07_followUsStepDef.assertOPenedURL(D07_followUsStepDef.java:60)
at ✽."https://demo.nopcommerce.com/new-online-store-is-open" is opened in new tab(file:///G:/Work/Selemuim/Projects/NopcommerceAutomationProject/src/main/resources/features/F07_followUs.feature:20)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase name="runScenario" time="19.019" classname="org.example.testRunner.Runners">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [https://demo.nopcommerce.com/iphone-6] but found [https://demo.nopcommerce.com/]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [https://demo.nopcommerce.com/iphone-6] but found [https://demo.nopcommerce.com/]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at org.example.stepDefs.D06_homeSlidersStepDef.asserCurrenURL(D06_homeSlidersStepDef.java:28)
at ✽.user should navigate to clickable URL "Iphone"(file:///G:/Work/Selemuim/Projects/NopcommerceAutomationProject/src/main/resources/features/F06_homeSliders.feature:10)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase name="runScenario" time="14.413" classname="org.example.testRunner.Runners"/>
  <system-out/>
  <testcase name="runScenario" time="13.883" classname="org.example.testRunner.Runners"/>
  <system-out/>
  <testcase name="runScenario" time="24.444" classname="org.example.testRunner.Runners"/>
  <system-out/>
  <testcase name="runScenario" time="15.339" classname="org.example.testRunner.Runners"/>
  <system-out/>
  <testcase name="runScenario" time="19.005" classname="org.example.testRunner.Runners"/>
  <system-out/>
  <testcase name="runScenario" time="36.049" classname="org.example.testRunner.Runners"/>
  <system-out/>
  <testcase name="runScenario" time="16.421" classname="org.example.testRunner.Runners"/>
  <system-out/>
  <testcase name="runScenario" time="11.329" classname="org.example.testRunner.Runners">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [https://demo.nopcommerce.com/nokia-lumia-1020] but found [https://demo.nopcommerce.com/]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [https://demo.nopcommerce.com/nokia-lumia-1020] but found [https://demo.nopcommerce.com/]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at org.example.stepDefs.D06_homeSlidersStepDef.asserCurrenURL(D06_homeSlidersStepDef.java:24)
at ✽.user should navigate to clickable URL "Nokia1020"(file:///G:/Work/Selemuim/Projects/NopcommerceAutomationProject/src/main/resources/features/F06_homeSliders.feature:6)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- org.example.testRunner.Runners -->
